platform :ios, '8.0'
use_frameworks!

target 'BetaLabs' do
    pod 'pop', '~> 1.0'
    pod 'Firebase'
    pod 'SwiftyJSON'
    pod 'Mapbox-iOS-SDK', '~> 3.2.3'
    pod 'RSKPlaceholderTextView'
    pod 'Haneke', '~> 1.0'
end

target 'BetaLabsTests' do
    
end
